### ISSUE TITLE
Panel calibration feature request.

### ISSUE THREAD

**Issue by afrankra** [Reveni-Matt/Camera-Tester#2]
Dear Matt, 
Thank you for your latest v1.6 Firmware. After over a month of testing, I came across something I perhaps could call a feature request.
I know the Tester self calibrates according to the documented process.
If I understand correctly, it uses the maximum panel Brightness and iterates backwards to find the right intensity that will match the heads sensors reading.
This effectively means that the tester is calibrated to the original light reference meter that measured the maximum Brightness of the panel originally.
I can ofcourse already change this value to match my own readings. And I have (16.9 -> 16.7) . This way I can have the meter and all my cameras calibrated to a reference light meter that I have access to.
Ideally the reference meter the testing person has access to would be NIST / EURAMET calibrated. (Just wanted to mention that I am aware of this).
In practice, it would be great to have an option to offset each setting of EV exposure with +- 0.1 EV value increments across the 16EV > 8 EV range.
This is essentially a compensation table that the user can input manually (after the auto calibration?) to fine tune each EV to match the reference meter.

I could for example make sure that all EVs displayed actually match my own meter instead of just the max value.

Would this compensating table / adjustment be possible?

**Comment by Reveni-Matt** [comment]
Have you found the other steps are not accurate?  I use a Sekonic 858 as my reference meter, it isn't NIST traceable but I think we are splitting hairs here.

After recalibrating at EV16.7 do you find your lower levels do not match within 0.1EV? I find they will read from 0.1 under to 0.1 over maximum deviation.  Mostly they read spot on.

The panel accuracy is probably more accurate in terms of total system accuracy for auto exposure mode than the sensor head is.  Meaning, improving panel accuracy further won't produce an improvement in system performance as the sensor head circuitry is the likely weakpoint already.

Individual step calibration like you describe is possible but would be a pretty big pain to implement.  The calibration sets the PWM rate that feeds the constant current supply for the LED panel, it is tuned with a 16 bit value and is multi-sampled many times to get the highest accuracy it can.  The bigger issue is the high speed sampling during a test, is not multisampled to reduce noise the way the calibration samples are.

**Comment by afrankra** [comment]
> Have you found the other steps are not accurate? I use a Sekonic 858 as my reference meter, it isn't NIST traceable but I think we are splitting hairs here.
After recalibrating at EV16.7 do you find your lower levels do not match within 0.1EV? I find they will read from 0.1 under to 0.1 over maximum deviation. Mostly they read spot on.

I think you are right, its splitting hairs considering that it would be too much work to implement.
It has more about reducing compounding errors. But I do fall under +-0.2 with my meter.

> The panel accuracy is probably more accurate in terms of total system accuracy for auto exposure mode than the sensor head is. 

My goal was to just have the panel output match the reference meter. (making it as inaccurate or accurate by tuning by hand). But is probably not worth the effort.

> Meaning, improving panel accuracy further won't produce an improvement in system performance as the sensor head circuitry is the likely weakpoint already.

I will close this then :) Thank you for the quick reply. I might open another one after taking some videos of some issues I got trying to deal with measurement accuracy in relation to sensor head placement.

**Comment by Reveni-Matt** [comment]
> I will close this then :) Thank you for the quick reply. I might open another one after taking some videos of some issues I got trying to deal with measurement accuracy in relation to sensor head placement.

I was able to solve some stuff in V1.6 where it would weird times if one of the sensors was obscured.

**Comment by Reveni-Matt** [comment]
@afrankra I added a new test firmware V1.7T2, it improves high speed curtain accuracy, give it a try if you want.
